# Generated by Django 5.2 on 2025-05-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
    ]
