# Generated by Django 5.2 on 2025-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default='2025-05-24 20:57'),
            preserve_default=False,
        ),
    ]
